import { CivicCase } from './types';
import { DEMO_POTHOLE_IMAGE, DEMO_WASTE_IMAGE, DEMO_WATER_IMAGE } from './demoImages';

export const INITIAL_DEMO_CASES: CivicCase[] = [
  {
    case_id: 'CV-2026-001',
    created_at: '2026-09-17T14:30:00Z',
    citizen_name: 'Rahul Verma',
    citizen_contact: '+91 98765-43210',
    complaint: 'Major deep pothole right at the corner of Stanley Road crossing. Water accumulates and two two-wheelers skidded last evening after dark.',
    image: DEMO_POTHOLE_IMAGE,
    media_type: 'photo',
    title: 'Hazardous Road Depression & Pothole at Stanley Road',
    category: 'ROADS',
    subcategory: 'Surface Asphalt Depression',
    citizen_summary: 'Your report describes a deep roadway pothole causing hazard to two-wheelers at Stanley Road intersection.',
    authority_summary: 'Structural asphalt cavity identified at intersection; recurring skidding incidents reported. Recommended quick cold-mix patch prior to resurfacing.',
    detailed_description: 'Citizen reports an approximate 1.2m wide, 15cm deep road cavity situated on the primary vehicular turning lane. High risk of accidents during night hours and monsoon runoff.',
    department: 'Road Maintenance & Infrastructure Division',
    responsible_authority: 'Municipal Public Works & Highway Authority',
    jurisdiction: 'Prayagraj Municipal Corporation, Civil Lines Ward',
    priority: 'HIGH',
    severity_score: 8.4,
    language: 'English',
    location: 'Stanley Road Crossing, Prayagraj, Uttar Pradesh',
    location_type: 'device_detected',
    coordinates: { lat: 25.4510, lng: 81.8432 },
    cluster_id: 'CLUSTER-PRAYAGRAJ-CIVIL-LINES',
    cluster_name: 'Prayagraj Civil Lines & Stanley Infrastructure Corridor',
    routing_decision: {
      authority: 'Municipal Public Works & Highway Authority',
      department: 'Road Maintenance & Infrastructure Division',
      jurisdiction: 'Prayagraj Municipal Corporation, Civil Lines Ward',
      endpoint: 'internal://dispatch/roads-infrastructure',
      routed_at: '2026-09-17T14:30:02Z',
      status: 'ROUTED',
      method: 'Automated AI Sovereign Router',
    },
    ai_verification: {
      verified: true,
      verification_summary: 'AI verified road surface asphalt cavity and vehicular hazard; automatic dispatch queued for Road Maintenance Division.',
      evidence_status: '1 photographic evidence item processed by Amazon Bedrock Vision',
      confidence_level: 'High (92%)',
    },
    citizen_impact: 'High commuter vulnerability for motorcyclists and cyclists; potential vehicle rim damage and sudden braking risks.',
    why_case_matters: 'Acute public transit safety hazard. The pothole sits on a turning trajectory where skidding events have already occurred; delay in repair during rain leads to sub-base pavement collapse.',
    recommended_action: [
      'Dispatch road safety hazard cones immediately',
      'Inspect asphalt sub-base stability and depth',
      'Deploy emergency cold-mix asphalt patch within 24h',
      'Schedule full bituminous overlay during weekly resurfacing cycle'
    ],
    action_steps_completed: [0, 1],
    evidence_observations: {
      detected_issue: 'Severe road surface asphalt failure',
      visible_evidence: 'Deep cratering with exposed aggregate and broken tarmac edges',
      potential_public_impact: 'Imminent collision or loss of vehicle balance',
      evidence_confidence: 'High'
    },
    safety_concern: 'Acute danger for two-wheelers and night pedestrians under low ambient light.',
    estimated_urgency: 'Urgent — Action recommended within 24 hours',
    confidence: 'Model confidence indicator: High (92%)',
    confidence_score: 92,
    status: 'IN_PROGRESS',
    assigned_officer: 'Officer A (Roads Div)',
    assigned_at: '2026-09-17T15:10:00Z',
    ai_generated: true,
    why_department: 'Classified under Public Works because roadway asphalt structural failures and municipal street resurfacing fall strictly within civil road engineering mandates.',
    ai_explanations: {
      why_category: 'The report indicates physical damage to the public transit surface affecting motor vehicle navigation.',
      why_department: 'Public Works Department handles road maintenance, potholes, and municipal transit pavement repair.',
      why_priority: 'High priority recommended due to active citizen safety incidents (two-wheeler skidding) and night-time hazard.',
      why_severity: 'Severity score 8.4 reflects active crash probability on a multi-modal arterial route.',
      why_action: 'Phased from immediate hazard cordoning to emergency patching and scheduled permanent restoration.'
    },
    potentially_related_cases: [
      {
        case_id: 'CV-2026-005',
        similarity_reason: 'Adjacent drainage blockage causing asphalt erosion 420m away',
        proximity_or_overlap: 'Approx. 420m away in Civil Lines/Stanley corridor'
      }
    ],
    audit_trail: {
      model: 'Amazon Bedrock Claude multimodal analysis',
      analyzed_at: '2026-09-17T14:30:04Z',
      reasoning_summary: 'Identified visual asphalt crater and vehicle skidding hazard; mapped to Public Works taxonomy and evaluated 420m correlation with CV-2026-005 drainage overflow.',
      input_modalities: ['Text (English)', 'Image (Asphalt Surface JPEG)'],
      human_governance_notice: 'Triage recommendation generated autonomously. Municipal Engineer retains statutory dispatch authorization.',
      latency_ms: 1140,
    },
    is_demo: true,
  },
  {
    case_id: 'CV-2026-002',
    created_at: '2026-09-17T11:15:00Z',
    citizen_name: 'Carlos Silva',
    citizen_contact: '+55 31 9988-7766',
    complaint: 'Há um acúmulo enorme de lixo na esquina da Rua Augusta com a Alameda Santos. O cheiro está insuportável e atraindo roedores há 3 dias.',
    image: DEMO_WASTE_IMAGE,
    media_type: 'photo',
    title: 'Solid Waste Accumulation & Vector Hazard at Rua Augusta',
    category: 'WASTE',
    subcategory: 'Uncollected Municipal Solid Waste',
    citizen_summary: 'Seu relatório descreve acúmulo de lixo orgânico causando odor e atração de vetores na esquina da Rua Augusta.',
    authority_summary: 'Uncollected municipal solid waste pile reported over a 72-hour window on high-foot-traffic commercial junction. Bio-sanitary risk from rodent attraction.',
    detailed_description: 'Citizen report submitted in Portuguese describing municipal waste container overflow and illegal dumping across pedestrian sidewalks, blocking pedestrian egress and raising vector disease risks.',
    department: 'Solid Waste & Environmental Sanitation Department',
    responsible_authority: 'Municipal Sanitation & Public Health Authority',
    jurisdiction: 'São Paulo Central Metropolitan Commercial District',
    priority: 'MEDIUM',
    severity_score: 6.8,
    language: 'Portuguese (BRICS Multilingual)',
    location: 'Rua Augusta / Alameda Santos, São Paulo, Brazil',
    location_type: 'device_detected',
    coordinates: { lat: -23.5596, lng: -46.6588 },
    cluster_id: 'CLUSTER-SAO-PAULO-CENTRAL',
    cluster_name: 'São Paulo Central Commercial Corridor',
    routing_decision: {
      authority: 'Municipal Sanitation & Public Health Authority',
      department: 'Solid Waste & Environmental Sanitation Department',
      jurisdiction: 'São Paulo Central Metropolitan Commercial District',
      endpoint: 'internal://dispatch/sanitation-waste',
      routed_at: '2026-09-17T11:15:02Z',
      status: 'ROUTED',
      method: 'Automated AI Sovereign Router',
    },
    ai_verification: {
      verified: true,
      verification_summary: 'AI processed Portuguese natural report, verified sidewalk waste overflow, and routed to Municipal Sanitation Authority.',
      evidence_status: '1 photographic evidence item processed by Amazon Bedrock Vision',
      confidence_level: 'High (89%)',
    },
    citizen_impact: 'Pedestrian sidewalk obstruction, offensive odor affecting local businesses and apartment residents, hygiene risk.',
    why_case_matters: 'Direct public health and commercial disruption in a high-density urban district. Uncollected organic refuse attracts disease vectors and degrades sidewalk accessibility.',
    recommended_action: [
      'Route municipal compactor collection vehicle to site',
      'Conduct street wash and sanitizing disinfectant spray',
      'Inspect neighborhood bin capacity and collection schedule',
      'Issue advisory notice to commercial food establishments on disposal hours'
    ],
    action_steps_completed: [],
    evidence_observations: {
      detected_issue: 'Sidewalk waste overflow and domestic refuse bags',
      visible_evidence: 'Torn plastic trash sacks and decomposing organic materials spilling onto pavement',
      potential_public_impact: 'Vector-borne disease transmission and pedestrian impediment',
      evidence_confidence: 'High'
    },
    safety_concern: 'Hygiene and pest infestation risk near commercial dining establishments.',
    estimated_urgency: 'Medium — Action recommended within 48 hours',
    confidence: 'Model confidence indicator: High (89%)',
    confidence_score: 89,
    status: 'AI_TRIAGED',
    assigned_officer: null,
    ai_generated: true,
    why_department: 'Routed to Municipal Sanitation as this department oversees municipal solid waste collection, dump clearance, and neighborhood street hygiene.',
    ai_explanations: {
      why_category: 'Refers to uncollected refuse and municipal domestic garbage piles.',
      why_department: 'Municipal Sanitation is the regulatory and operational body managing refuse disposal and sidewalk washing.',
      why_priority: 'Medium priority because while not an immediate structural hazard, persistent 3-day accumulation poses public health hazards.',
      why_severity: 'Severity score 6.8 accounts for urban density and vector attraction.',
      why_action: 'Focuses on immediate collection followed by disinfection and scheduling review.'
    },
    audit_trail: {
      model: 'Amazon Bedrock Claude multilingual multimodal analysis',
      analyzed_at: '2026-09-17T11:15:05Z',
      reasoning_summary: 'Parsed Portuguese natural vernacular; extracted commercial street intersection; categorized under Limpeza Urbana / Municipal Sanitation with vector risk score 6.8.',
      input_modalities: ['Text (Portuguese)', 'Image (Refuse Heap JPEG)'],
      human_governance_notice: 'Requires municipal sanitation crew verification before closing ticket.',
      latency_ms: 1220,
    },
    is_demo: true,
  },
  {
    case_id: 'CV-2026-003',
    created_at: '2026-09-17T09:40:00Z',
    citizen_name: 'Amit Patel',
    citizen_contact: 'amit.patel@delhicivic.in',
    complaint: 'Three consecutive streetlights along Outer Circle Block C have been completely dark for four nights. The dark alley makes pedestrians feel unsafe after 8 PM.',
    media_type: 'none',
    title: 'Consecutive Streetlight Luminaire Outage at Block C',
    category: 'STREETLIGHT',
    subcategory: 'Electrical Grid / Luminaire Failure',
    citizen_summary: 'Your report highlights 3 inactive street lights creating a dark zone along Block C Outer Circle.',
    authority_summary: 'Trio of sequential LED luminaires out of service. Suspected feeder pillar breaker trip or circuit cable discontinuity along municipal grid.',
    detailed_description: 'Citizen expresses public safety anxiety due to prolonged illumination failure covering an approximate 90-meter pedestrian pathway in a dense commercial and transit zone.',
    department: 'Street Lighting & Power Distribution Division',
    responsible_authority: 'Municipal Electrical & Public Lighting Authority',
    jurisdiction: 'New Delhi Municipal Council, Connaught Ward',
    priority: 'MEDIUM',
    severity_score: 6.2,
    language: 'English',
    location: 'Outer Circle Block C, Connaught Place, New Delhi',
    location_type: 'manual',
    coordinates: { lat: 28.6328, lng: 77.2197 },
    cluster_id: 'CLUSTER-DELHI-CP-TRANSIT',
    cluster_name: 'New Delhi Connaught Place Pedestrian Zone',
    routing_decision: {
      authority: 'Municipal Electrical & Public Lighting Authority',
      department: 'Street Lighting & Power Distribution Division',
      jurisdiction: 'New Delhi Municipal Council, Connaught Ward',
      endpoint: 'internal://dispatch/electrical-lighting',
      routed_at: '2026-09-17T09:40:02Z',
      status: 'ROUTED',
      method: 'Automated AI Sovereign Router',
    },
    ai_verification: {
      verified: true,
      verification_summary: 'AI verified dark corridor safety concern; dispatched to Municipal Electrical & Public Lighting Authority.',
      evidence_status: 'Textual observation corroborated by historical circuit telemetry',
      confidence_level: 'High (94%)',
    },
    citizen_impact: 'Pedestrian insecurity, diminished nighttime surveillance visibility, higher vulnerability for evening commuters.',
    why_case_matters: 'Night illumination failure in high-footfall metro interchange zone creates vulnerability for women and late-evening commuters, reducing CCTV deterrent coverage.',
    recommended_action: [
      'Test feeder pillar switch and automated photocell timer',
      'Inspect cable continuity and underground junction box',
      'Replace burnt LED driver or damaged luminaire modules',
      'Verify restoration via smart lighting telemetry portal'
    ],
    action_steps_completed: [0],
    evidence_observations: {
      detected_issue: 'Unlit municipal light poles along sidewalk',
      visible_evidence: 'Inoperative lamp heads with no luminous output during evening hours',
      potential_public_impact: 'Reduced public safety and pedestrian vulnerability',
      evidence_confidence: 'Medium'
    },
    safety_concern: 'Diminished public safety perception and risk of opportunistic street crimes.',
    estimated_urgency: 'Medium — Resolve within 48 to 72 hours',
    confidence: 'Model confidence indicator: High (94%)',
    confidence_score: 94,
    status: 'ASSIGNED',
    assigned_officer: 'Officer B (Electrical)',
    assigned_at: '2026-09-17T11:00:00Z',
    ai_generated: true,
    why_department: 'Electrical & Public Lighting Department manages municipal power poles, underground wiring, and street luminaires.',
    ai_explanations: {
      why_category: 'Directly concerns illumination infrastructure and public light fixtures.',
      why_department: 'Public Lighting Department holds jurisdiction over electrical substations and street poles.',
      why_priority: 'Medium priority; lights are critical for public safety deterrence, though physical roadway is unobstructed.',
      why_severity: 'Severity score 6.2 reflects multi-luminaire dark pocket in a high-footfall metropolitan sector.',
      why_action: 'Focuses on diagnostic circuit testing and rapid luminaire replacement.'
    },
    audit_trail: {
      model: 'Amazon Bedrock Claude text analysis',
      analyzed_at: '2026-09-17T09:40:03Z',
      reasoning_summary: 'Evaluated 4-night multi-pole luminaire outage; identified Connaught Place commercial quadrant; routed to Electrical Dept with safety weighting.',
      input_modalities: ['Text (English)'],
      human_governance_notice: 'Electrical circuit breaker status requires ground technician multi-meter testing.',
      latency_ms: 980,
    },
    is_demo: true,
  },
  {
    case_id: 'CV-2026-004',
    created_at: '2026-09-16T18:20:00Z',
    citizen_name: 'Priya Sharma',
    citizen_contact: 'priya.sharma@civicmail.org',
    complaint: 'Potable water main line has cracked near the primary school gate. Clean treated water has been gushing onto the road since morning, flooding the footpath.',
    image: DEMO_WATER_IMAGE,
    media_type: 'photo',
    title: 'High-Volume Potable Water Main Pipe Burst',
    category: 'WATER',
    subcategory: 'Municipal Pressurized Water Main Fracture',
    citizen_summary: 'Your report indicates a fractured drinking water pipe flooding the footpath near the school gate.',
    authority_summary: 'Pressurized distribution pipeline leak resulting in significant loss of treated water and localized sidewalk flooding in proximity to school zone.',
    detailed_description: 'Substantial volumetric water loss reported outside public school entrance. Gushing water threatens to saturate sub-road soil and creates water pressure drop for adjacent residential wards.',
    department: 'Potable Water Pipeline & Sewerage Division',
    responsible_authority: 'Municipal Water Supply & Sewerage Board',
    jurisdiction: 'eThekwini Metropolitan Municipality, Durban Urban Ward',
    priority: 'CRITICAL',
    severity_score: 9.1,
    language: 'English',
    location: 'Florida Road School Zone, Durban, South Africa',
    location_type: 'device_detected',
    coordinates: { lat: -29.8372, lng: 31.0163 },
    cluster_id: 'CLUSTER-DURBAN-FLORIDA-ROAD',
    cluster_name: 'Durban Florida Road School Precinct',
    routing_decision: {
      authority: 'Municipal Water Supply & Sewerage Board',
      department: 'Potable Water Pipeline & Sewerage Division',
      jurisdiction: 'eThekwini Metropolitan Municipality, Durban Urban Ward',
      endpoint: 'internal://dispatch/water-sewerage',
      routed_at: '2026-09-16T18:20:02Z',
      status: 'ROUTED',
      method: 'Automated AI Sovereign Router',
    },
    ai_verification: {
      verified: true,
      verification_summary: 'AI verified critical potable water surge; immediate isolation recommended to prevent school sidewalk washout.',
      evidence_status: '1 photographic evidence item processed by Amazon Bedrock Vision',
      confidence_level: 'High (96%)',
    },
    citizen_impact: 'Loss of valuable municipal treated drinking water; pedestrian crossing disruption for school children; water supply shortage to nearby blocks.',
    why_case_matters: 'Immediate risk of soil cavitation / sinkhole directly beside school gate. Continuous treated water loss exceeds 4,000 liters/hour while depleting municipal pressure.',
    recommended_action: [
      'Isolate zone distribution valve to stem immediate flooding',
      'Excavate pipeline joint to identify rupture classification',
      'Install heavy-duty repair clamp or replace ductile iron pipe section',
      'Conduct pressure testing and chlorination test before restoring supply'
    ],
    action_steps_completed: [0, 1],
    evidence_observations: {
      detected_issue: 'Underground pressurized pipe fracture',
      visible_evidence: 'Clear water bubbling upward through road joint and running across sidewalk',
      potential_public_impact: 'Critical water wastage, foundation erosion, and community water supply disruption',
      evidence_confidence: 'High'
    },
    safety_concern: 'Flooding near school entrance and potential soil cavitation beneath paved road.',
    estimated_urgency: 'Critical — Immediate dispatch required (< 6 hours)',
    confidence: 'Model confidence indicator: High (96%)',
    confidence_score: 96,
    status: 'IN_PROGRESS',
    assigned_officer: 'Officer C (Water Board)',
    assigned_at: '2026-09-16T19:00:00Z',
    ai_generated: true,
    why_department: 'Water & Sewerage Board is solely equipped and authorized to operate isolation gate valves and repair municipal pressurized mains.',
    ai_explanations: {
      why_category: 'Primary incident is treated municipal drinking water pipeline fracture.',
      why_department: 'Water Board maintains municipal underground conduits and isolation valves.',
      why_priority: 'Critical priority due to continuous resource wastage, risk of sinkhole formation, and proximity to school children.',
      why_severity: 'Severity score 9.1 reflects severe resource loss and school zone vulnerability.',
      why_action: 'Requires immediate hydraulic valve shutoff followed by trench excavation and pipe renewal.'
    },
    audit_trail: {
      model: 'Amazon Bedrock Claude multimodal analysis',
      analyzed_at: '2026-09-16T18:20:06Z',
      reasoning_summary: 'Detected pressurized fountain surge from pavement; flagged school zone proximity; triggered CRITICAL priority with 9.1 severity score.',
      input_modalities: ['Text (English)', 'Image (Water Main Fountain Surge JPEG)'],
      human_governance_notice: 'Valve isolation must be performed by certified municipal hydraulic technicians.',
      latency_ms: 1050,
    },
    is_demo: true,
  },
  {
    case_id: 'CV-2026-005',
    created_at: '2026-09-16T10:00:00Z',
    citizen_name: 'Sunil Kumar',
    citizen_contact: '+91 98112-23344',
    complaint: 'Stormwater drain is completely choked with silt and construction debris near Civil Lines. Sludge is overflowing onto the road side.',
    media_type: 'none',
    title: 'Stormwater Conduit Clogging & Overflow',
    category: 'DRAINAGE',
    subcategory: 'Stormwater Culvert Siltation',
    citizen_summary: 'Your report describes a clogged stormwater drain overflowing sludge onto the road in Civil Lines.',
    authority_summary: 'Sediment and building debris blockage in primary stormwater arterial culvert causing blackwater back-up and asphalt soaking in Civil Lines corridor.',
    detailed_description: 'Culvert blockage of over 70% cross-section obstructing natural drainage outflow. Causes stagnant ponding that degrades road bitumen and attracts mosquitoes.',
    department: 'Potable Water Pipeline & Sewerage Division',
    responsible_authority: 'Municipal Water Supply & Sewerage Board',
    jurisdiction: 'Prayagraj Municipal Corporation, Civil Lines Ward',
    priority: 'MEDIUM',
    severity_score: 7.2,
    language: 'English',
    location: 'Civil Lines Arterial Road, Prayagraj, Uttar Pradesh',
    location_type: 'manual',
    coordinates: { lat: 25.4535, lng: 81.8465 },
    cluster_id: 'CLUSTER-PRAYAGRAJ-CIVIL-LINES',
    cluster_name: 'Prayagraj Civil Lines & Stanley Infrastructure Corridor',
    routing_decision: {
      authority: 'Municipal Water Supply & Sewerage Board',
      department: 'Potable Water Pipeline & Sewerage Division',
      jurisdiction: 'Prayagraj Municipal Corporation, Civil Lines Ward',
      endpoint: 'internal://dispatch/water-sewerage',
      routed_at: '2026-09-16T10:00:02Z',
      status: 'ROUTED',
      method: 'Automated AI Sovereign Router',
    },
    ai_verification: {
      verified: true,
      verification_summary: 'AI detected culvert siltation and cross-referenced with Stanley Road roadbed erosion cluster.',
      evidence_status: 'Textual observation cross-checked against municipal drainage grid',
      confidence_level: 'High (90%)',
    },
    citizen_impact: 'Odor, mosquito breeding habitat, localized flooding during rain, asphalt deterioration.',
    why_case_matters: 'Root cause for neighboring road deterioration (CV-2026-001). Clogged stormwater saturates surrounding road foundations, leading directly to pothole cratering.',
    recommended_action: [
      'Deploy suction cum jetting machine to desilt culvert',
      'Remove construction rubble obstructing inlet grating',
      'Apply larvicidal treatment to prevent mosquito proliferation',
      'Inspect upstream catchment for unauthorized dumping'
    ],
    action_steps_completed: [0, 1, 2, 3],
    evidence_observations: {
      detected_issue: 'Blocked stormwater channel with silt and rubble',
      visible_evidence: 'Stagnant dark water and debris visible above drain grate level',
      potential_public_impact: 'Sanitary nuisance, road edge erosion, and vector breeding',
      evidence_confidence: 'High'
    },
    safety_concern: 'Stagnant wastewater posing vector disease risks and roadway destabilization.',
    estimated_urgency: 'Standard — Resolve within 72 hours',
    confidence: 'Model confidence indicator: High (90%)',
    confidence_score: 90,
    status: 'RESOLVED',
    assigned_officer: 'Officer A (Roads Div)',
    assigned_at: '2026-09-16T11:00:00Z',
    resolved_at: '2026-09-17T08:00:00Z',
    ai_generated: true,
    why_department: 'Drainage & Stormwater Authority has specialized high-pressure jetting and vacuum desilting units.',
    ai_explanations: {
      why_category: 'Concerns sub-surface stormwater culvert blockage and surface drainage flow.',
      why_department: 'Drainage Authority manages municipal stormwater grates and desilting equipment.',
      why_priority: 'Medium priority as flow is partially obstructed but not currently flooding occupied structures.',
      why_severity: 'Severity score 7.2 due to potential compound damage to road asphalt and monsoon risk.',
      why_action: 'Mandates mechanical suction desilting followed by larvicidal spraying.'
    },
    potentially_related_cases: [
      {
        case_id: 'CV-2026-001',
        similarity_reason: 'Water runoff and road surface degradation along connected Stanley Road / Civil Lines corridor',
        proximity_or_overlap: 'Approx. 420m away in Prayagraj sector'
      }
    ],
    audit_trail: {
      model: 'Amazon Bedrock Claude text and spatial correlation analysis',
      analyzed_at: '2026-09-16T10:00:04Z',
      reasoning_summary: 'Identified culvert siltation; correlated with Stanley Road catchment basin; recommended desilting and cross-checked against road erosion.',
      input_modalities: ['Text (English)'],
      human_governance_notice: 'Resolution certified with field inspection log by Municipal Junior Engineer.',
      latency_ms: 1100,
    },
    is_demo: true,
  }
];
